sonar.projectKey=aysimatalantmr
sonar.organization=aysimatalantmr

# Python projesi olduğunu ve kodların nerede olduğunu belirtiyoruz
sonar.sources=core, ai_detector
sonar.python.version=3.12

# Taranmasını İSTEMEDİĞİMİZ dosyalar (Sanal ortamlar, html'ler vs.)
sonar.exclusions=**/migrations/**, **/venv/**, **/*.html, **/*.css, manage.py