name: Doxygen Dokumantasyonunu Uret ve Yayinla

on:
  push:
    branches: ["main", "master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v4

      - name: Doxygen ve Graphviz Kur
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Semalari ve Dokumani Olustur
        # ÖNEMLİ: Eğer dosyanın adı sadece 'Doxyfile' ise burayı düzelt!
        run: doxygen Doxyfile.properties

      # --- PDF OLUŞTURMA VE İNDİRME ADIMLARI ---
      - name: Install LaTeX Components
        run: sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended gnuplot

      - name: Compile Doxygen PDF
        run: |
          cd docs_latex
          make

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Proje-Doxygen-PDF-Raporu
          path: docs_latex/refman.pdf

          # --- HTML SİTESİNİ YAYINLAMA ADIMI ---
      - name: GitHub Pages ile Web Sitesi Olarak Yayinla
        uses: peaceiris/actions-gh-pages@4f610d228e0298a08d66dcbdcb850d53c306d812 # v4 versiyonu
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs_html

    
